apiVersion: 1

datasources:
  - name: Loki DEV
    uid: PD5A68A3BD6F8BA56
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false
    jsonData:
      maxLines: 1000

  - name: Prometheus DEV
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
    jsonData:
      timeInterval: 15s

  - name: AI-GM Story DB DEV
    uid: ai_gm_sqlite_story
    type: frser-sqlite-datasource
    access: proxy
    jsonData:
      path: /var/lib/ai-gm-db/ai_gm.db
    editable: false
