apiVersion: 1

datasources:
  - name: AI-GM Story DB
    uid: ai_gm_sqlite_story
    type: frser-sqlite-datasource
    access: proxy
    jsonData:
      path: /var/lib/ai-gm-db/ai_gm.db
    editable: false
