#!/usr/bin/env bash
# sync_fix_list_from_board.sh
# Mirrors the "To Do" column of the ClaudeCodeUI GitHub Issues Board into the
# auto-managed BOARD-TODO block of fix_list.md.
#
# The board is NOT GitHub Projects — it is the ClaudeCodeUI plugin's Kanban
# computed purely from issue state + labels (see github-issues.service.js):
#   To Do        = state:open  AND none of the status labels
#   In Progress  = state:open  AND label "in-progress"
#   In Review    = state:open  AND label "review"
#   Blocked      = state:open  AND label "blocked"
#   Done         = state:closed
# => Only the `repo` scope is needed (no read:project, no Projects API).
#
# USAGE:  bash scripts/sync_fix_list_from_board.sh
# Idempotent: rewrites only the BOARD-TODO block in fix_list.md.

set -euo pipefail

OWNER_REPO="szmidtpiotr/ai-gm"
FIX_LIST="$(cd "$(dirname "$0")/.." && pwd)/fix_list.md"

# All OPEN issues (= not Done), each tagged with its board column from labels.
# Column rule (ClaudeCodeUI github-issues.service.js):
#   label in-progress -> In Progress | review -> In Review | blocked -> Blocked | else -> To Do
todo="$(gh issue list --repo "$OWNER_REPO" --state open --limit 400 \
  --json number,title,labels \
  --jq 'sort_by(.number) | .[]
        | (.labels | map(.name)) as $l
        | (if   ($l|index("in-progress")) then "IN PROGRESS"
           elif ($l|index("review"))      then "IN REVIEW"
           elif ($l|index("blocked"))     then "BLOCKED"
           else "TO DO" end) as $c
        | "- [ ] #\(.number) `[\($c)]` — \(.title)"')"

count="$(printf '%s\n' "$todo" | grep -c '^- ' || true)"

START="<!-- BOARD-TODO:START (auto-generated by sync_fix_list_from_board.sh — do not edit by hand) -->"
END="<!-- BOARD-TODO:END -->"
stamp="$(date -u +%Y-%m-%dT%H:%MZ 2>/dev/null || echo manual-run)"

new_section="$START
## BOARD — otwarte issues (auto-sync z ClaudeCodeUI Issues Board, $count pozycji, $stamp)
_Wszystkie niezamknięte, tagowane kolumną. Do auto-wdrożenia: \`[TO DO]\` + \`[IN REVIEW]\` (In Review = sprawdź komentarze — Piotr mógł odpowiedzieć/zatwierdzić). Pomijaj \`[IN PROGRESS]\` / \`[BLOCKED]\` i feature (chyba że wskazane)._
$todo
$END"

tmp="$(mktemp)"
if grep -q "BOARD-TODO:START" "$FIX_LIST"; then
  awk -v repl="$new_section" '
    $0 ~ /BOARD-TODO:START/ {print repl; skip=1; next}
    $0 ~ /BOARD-TODO:END/   {skip=0; next}
    skip!=1 {print}
  ' "$FIX_LIST" > "$tmp"
else
  awk -v repl="$new_section" 'NR==1{print; print ""; print repl; print ""; next} {print}' "$FIX_LIST" > "$tmp"
fi
cat "$tmp" > "$FIX_LIST" && rm -f "$tmp"   # cat (not mv) — sshfs uid mismatch breaks mv ownership
chmod 664 "$FIX_LIST" 2>/dev/null || true   # keep group-writable (sshfs writes drop to 600 → breaks git add as piotrszmidt)

echo "Synced $count To Do issue(s) into $FIX_LIST" >&2
