#!/usr/bin/env python3
"""
Generate map-overlay.json from open GitHub issues.

Mechanical, no LLM. For each OPEN issue it reads the '## Files changed' section
of the body, maps each file path to a map node id via node-map.json, and records
the issue as a BUG (red badge) or FIX (green badge) on that node.

The 'heat' registry (runtime calls/errors per node) is left untouched here — it is
written by update_heat.py once observability (Phase 11 game_events/llm_call_log)
exists. This way issues stay fresh daily without touching runtime data.

Usage:
    python3 update_overlay.py                       # uses gh in the current repo
    python3 update_overlay.py --repo owner/name     # explicit repo
    python3 update_overlay.py --dry-run             # print, don't write

Requires: gh CLI authenticated, python3. Run on a host that has gh + repo access.
"""
import json, subprocess, sys, re, os, argparse
from pathlib import Path

HERE = Path(__file__).resolve().parent
NODE_MAP = HERE / "node-map.json"
OUT = HERE / "map-overlay.json"

def load_node_map():
    data = json.loads(NODE_MAP.read_text())
    # longest path first so the most specific prefix wins
    return sorted(data["paths"].items(), key=lambda kv: -len(kv[0]))

def path_to_node(path, paths):
    path = path.strip().strip("`").lstrip("./")
    for prefix, node in paths:
        if path == prefix or path.startswith(prefix):
            return node
    return None

FILES_HEADER = re.compile(r"^#+\s*Files? changed", re.I)
PATH_RE = re.compile(r"`?([\w./-]+\.\w+)`?")

def extract_paths(body):
    """Pull file paths from the '## Files changed' section of an issue body."""
    if not body:
        return []
    lines = body.splitlines()
    out, in_section = [], False
    for ln in lines:
        if FILES_HEADER.match(ln.strip()):
            in_section = True
            continue
        if in_section:
            if ln.strip().startswith("#"):   # next section ends it
                break
            for m in PATH_RE.finditer(ln):
                cand = m.group(1)
                if "/" in cand:              # ignore bare filenames / versions
                    out.append(cand)
    return out

def gh_issues(repo):
    cmd = ["gh", "issue", "list", "--state", "open",
           "--json", "number,title,labels,body", "--limit", "500"]
    if repo:
        cmd += ["--repo", repo]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        sys.exit(f"gh failed: {res.stderr.strip()}")
    return json.loads(res.stdout)

def classify(labels):
    names = {l["name"].lower() for l in labels}
    if "bug" in names:
        return "bug"
    if names & {"enhancement", "needs-testing", "feature"}:
        return "fix"
    return "fix"   # default: treat open work as a planned fix

def severity(labels):
    names = {l["name"].lower() for l in labels}
    if "critical" in names or "p0" in names: return "high"
    if "p1" in names: return "med"
    return "med"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=os.environ.get("ARCHMAP_REPO"))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    paths = load_node_map()
    issues = gh_issues(args.repo)

    bugs, fixes = {}, {}
    matched = 0
    for iss in issues:
        nodes = set()
        for p in extract_paths(iss.get("body", "")):
            n = path_to_node(p, paths)
            if n:
                nodes.add(n)
        if not nodes:
            continue
        matched += 1
        kind = classify(iss.get("labels", []))
        for n in nodes:
            if kind == "bug":
                bugs.setdefault(n, []).append({
                    "sev": severity(iss.get("labels", [])),
                    "ref": f"#{iss['number']}",
                    "t": iss["title"][:90],
                })
            else:
                fixes.setdefault(n, []).append({
                    "n": iss["number"],
                    "t": iss["title"][:90],
                })

    # preserve existing heat
    heat = {}
    if OUT.exists():
        try:
            heat = json.loads(OUT.read_text()).get("heat", {})
        except Exception:
            pass

    repo = args.repo
    if not repo:
        r = subprocess.run(["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"],
                           capture_output=True, text=True)
        repo = r.stdout.strip() or "szmidtpiotr/ai-gm"

    out = {
        "_doc": "AUTO-GENERATED by update_overlay.py. Edits are overwritten.",
        "repo": repo,
        "generated_at": subprocess.run(["date", "-u", "+%Y-%m-%dT%H:%MZ"],
                                       capture_output=True, text=True).stdout.strip(),
        "bugs": bugs, "fixes": fixes, "heat": heat,
    }
    txt = json.dumps(out, indent=2, ensure_ascii=False)
    print(f"issues scanned: {len(issues)} · matched to nodes: {matched} · "
          f"bug-nodes: {len(bugs)} · fix-nodes: {len(fixes)}")
    if args.dry_run:
        print(txt)
    else:
        OUT.write_text(txt + "\n")
        print(f"wrote {OUT}")

if __name__ == "__main__":
    main()
